version: 2
jobs:
  build:
    docker:
    - image: python:3.6-stretch
    steps:
    - checkout
    - run: python3 -m venv ~/venv
    - run: ~/venv/bin/pip install -U pip wheel
    - run: ~/venv/bin/pip install https://github.com/pyvec/pyvo.cz/archive/master.zip
    - run: ~/venv/bin/python -m pyvocz --help
    - run: mkdir /tmp/artifacts
    - run:
        name: python -m pyvocz + wget --mirror
        command: |
          set -x
          ~/venv/bin/python -m pyvocz --data=$PWD >/tmp/artifacts/app.log 2>&1 &
          sleep 3
          cd /tmp
          wget --no-verbose --mirror --adjust-extension --convert-links --reject-regex '/201[012345679]' \
               http://127.0.0.1:5000/ >/tmp/artifacts/wget.log 2>&1 || true
          ls -lah
          tail /tmp/artifacts/*.log
          find 127.0.0.1:5000 -type f | xargs sed -i 's|http://fonts|https://fonts|g'
          mv -vi 127.0.0.1:5000/* /tmp/artifacts/
    - run: export
    - store_artifacts:
        path: /tmp/artifacts
workflows:
  version: 2
  build_and_test:
    jobs:
    - build
