version: 2
jobs:
  build:
    docker:
    - image: python:3.6-stretch
    steps:
    - checkout
    - run: pwd
    - run: python3 -m venv ~/venv
    - run: ~/venv/bin/pip install -U pip wheel
    - run: ~/venv/bin/pip install https://github.com/pyvec/pyvo.cz/archive/master.zip
    - run: ~/venv/bin/python -m pyvocz --help
    - run: ls -lah
    - run: mkdir /tmp/artifacts
    - run: date >> /tmp/artifacts/index.html
    - store_artifacts:
        path: /tmp/artifacts
workflows:
  version: 2
  build_and_test:
    jobs:
    - build
